### ISSUE TITLE
Option to not wrap URL's in []

### ISSUE THREAD

**Issue by justmobilize** [werk85/node-html-to-text#111]
I understand using the [] around URL's to give it the button look, but is there a way to turn these off?

**Comment by royalcrown28** [comment]
Same, This is preventing my parsed images from embedding

**Comment by alex1702** [comment]
i have make a pr #119 to solve this.

**Comment by KillyMXI** [comment]
This should've been closed long ago. PR #119 was merged. `noLinkBrackets` option gives the desired effect.
