### ISSUE TITLE
Not work ignoreImage & ignoreHref

### ISSUE THREAD

**Issue by MrHidalgo** [werk85/node-html-to-text#114]
`cat /dist/index.html | html-to-text --ignoreHref=true --ignoreImage=true > text.txt`
mb i wrote wrong...

**Comment by mlegenhausen** [comment]
See following lines for the command line interface:

https://github.com/werk85/node-html-to-text/blob/master/bin/cli.js#L27-L28

All command line parameters need to be dash-cased.
