### ISSUE TITLE
ordered lists ignore the start= attribute

### ISSUE THREAD

**Issue by mattbailey** [werk85/node-html-to-text#117]
e.g. 
```html
<ol start="2">
  <li>foo</li>
</ol>
```

produces:
```
1. foo
```

**Comment by mlegenhausen** [comment]
Yes the start attribute is not support. It shouldn't be that hard to provide this feature.

Take a look at https://github.com/werk85/node-html-to-text/blob/master/lib/formatter.js#L134 where I think we simply need to add the `start` value on top of the `index`. Would be nice if you could provide a pull request.

**Comment by mattbailey** [comment]
PR added: https://github.com/werk85/node-html-to-text/pull/118
