### ISSUE TITLE
<sup>has additional space

### ISSUE THREAD

**Issue by datenwort** [werk85/node-html-to-text#125]
Hi,

thank your for this library. Very nice work.

When i try to convert a text containing a `<sup>` an additional space. (Is the same for strong, b ...)

```
var htmlToText = require('html-to-text');
var text = htmlToText.fromString('<p>This text contains <sup>superscript</sup> text.</p>', { wordwrap: false, preserveNewlines: true, singleNewLineParagraphs: true });
console.log(text);
```

I got the text with an additional space between superscript and text.
```
This text contains superscript  text.
```

Is there a workaround?

**Comment by mlegenhausen** [comment]
There is currently no workaround. I think the problem needs to be fixed in the library. Pull requests are welcome.

**Comment by fgcui1204** [comment]
need to merge that PR,thanks @mlegenhausen
