### ISSUE TITLE
urls with '#' symbol are ignored

### ISSUE THREAD

**Issue by vohtaski** [werk85/node-html-to-text#135]
Expected behaviour:
Url with '#' is shown in the output

How to reproduce
```
echo '<a href="http://localhost:3002/#/reset/123">Reset my password</a>' | html-to-text
-> Reset my password

echo '<a href="http://localhost:3002/reset/123">Reset my password</a>' | html-to-text
-> Reset my password [http://localhost:3002/reset/123]
```

Is there a workaround?

**Comment by mhagmajer** [comment]
@vohtaski, you set option `noAnchorUrl` to `false` to disable this behavior.

More: https://github.com/werk85/node-html-to-text/blob/5419826c5394bbab6c5fd67c23b00364c6ebedee/lib/formatter.js#L79

**Comment by vohtaski** [comment]
Thanks, it works!
