### ISSUE TITLE
Sending shell command through PHP produces empty .txt file instead of output

### ISSUE THREAD

**Issue by Fejwin** [werk85/node-html-to-text#170]
Running in shell:
`C:\> html-to-text < D:\test.html --tables=true --wordwrap=false > D:\test.txt`
produces proper output.
Instead trying to run in PHP script:
`<?php
exec('html-to-text < D:\\test.html --tables=true --wordwrap=false > D:\\test.txt');
?>`
produces an empty test.txt file. What goes wrong, how to make the script work through php?

**Comment by mlegenhausen** [comment]
Seems not be a problem with `html-to-text`. Closed for now.
