### ISSUE TITLE
Anybody home? (status of this project)

### ISSUE THREAD

**Issue by KillyMXI** [werk85/node-html-to-text#198]
It seems like there is no one to provide even basic maintenance and accept PRs.

Maybe it's time to pass on the project to a different maintainer or to fork it in case the former is not possible?

Project activity is weird though. Waiting for some day in April to see another batch of activity and then another year of silence?

**Comment by KillyMXI** [comment]
Until we have any response, I made a usable fork.

I've updated the dependencies and merged a bunch of patches to my fork: https://github.com/KillyMXI/node-html-to-text
(Should I open issues and provide support there - I haven't decided yet.)

I've published my fork into a scoped package: https://www.npmjs.com/package/@mxiii/html-to-text

Anyone who need a patched version right now - can install it by replacing `html-to-text` with `@mxiii/html-to-text` in `package.json` and at the place of import.

**Comment by netmiller** [comment]
Hard to find alternatives AFAIK (for Node). This or fork is quite important in my project.

**Comment by KillyMXI** [comment]
Yep. I did some research, and all alternative JS packages are either:

* primitive;
* outdated;
* serve different purpose;
* combination of those.

Nowhere to run.

**Comment by mlegenhausen** [comment]
Sorry guys. I am not using this packages anymore by myself and have not the time to further maintain this project. But I am open for contributors that would like the maintain the project.

**Comment by KillyMXI** [comment]
Yay, finally a response.

I use it for a couple of tiny projects.
I'm not ready to invest into feature development, but at least I'm ready to keep the communication and to keep the package healthy.

**Comment by KillyMXI** [comment]
I've noticed @madflow (@priotas) is actively working on a separate fork now.
Can they share plans with us?

**Comment by madflow** [comment]
@KillyMXI  We are using this in a non-critical part in one of our products. In my experience: If a package/module is not maintained anymore you can might as well maintain a fork. Since I predict there will be no aspiring maintainers jumping up in order to hack on a html-email-to-text-converter (thanks @mlegenhausen for taking one for the team) I made myself a little bit more comfortable and:

- Migrated to Typescript
- Migrated to Jest
- Removed cli and minimist
- Removed `.fromString`
- Removed Browser support
- Yarn instead of NPM

Tests pass...

Anyone: Feel free to pull from https://github.com/priotas/html-to-text/tree/next. We will publish this under `@priotas/html-to-text`

**Comment by KillyMXI** [comment]
I wonder how many people rely on CLI and browser support.
If there is a need for that, then a separate package is still needed.

I will keep a backwards compatible package.

**Comment by netmiller** [comment]
CLI is nice for testing etc, but I need only Nodejs. No need for browser support but I can imagine someone will need.

**Comment by KillyMXI** [comment]
@mlegenhausen  If you want an explicit request from a potential maintainer - you have one.

* few things still itch my OCD;
* maintaining a fork has limited effect for community;
* I'm hesitant to diverge far from main code base (any cleanup will make it harder to merge back future contributions).

So I would like to resolve this by maintaining the original package.

(And please don't be silent in case you don't want to approve this and waiting for a better offer.)

**Comment by JohnMcLear** [comment]
+1 please resolve this asap :)

**Comment by mlegenhausen** [comment]
@KillyMXI I added you as maintainer of the project.

**Comment by JohnMcLear** [comment]
Excellently handled @mlegenhausen and @KillyMXI- credit to you both.

Now let's get this party started 🔢

**Comment by KillyMXI** [comment]
Thank you.

I will open a tracking issue for the next version in a day, and then start working on it.

Next version going to be 6.0.0. I will keep backwards compatibility, but I might need to bump Node version.

**Comment by JohnMcLear** [comment]
@KillyMXI FWIW Etherpad is shifting to require Node10+ in our next release.

**Comment by KillyMXI** [comment]
I opened #200 to track the progress towards 6.0.0.
Those waiting for new version can subscribe to that issue.
I would expect it to be done in few batc
hes during a week. But I also got some urgent matter to take care of, so there might be little delays.
This issue served it's purpose and closed.
