### ISSUE TITLE
Allow to disable wordwrap

### ISSUE THREAD

**Issue by tepez** [werk85/node-html-to-text#34]
I use `node-html-to-text` to convert html content before writing it to csv/xlsx file.
I don't want word wrapping when doing so.

I currently pass `{ wordwrap: NaN }` and this disables word wrapping (because `length + word.length` always `< NaN` (wordwrap() in helper.js).

I suggest that `{ wordwrap: null }` would be used to disable word wrapping.

**Comment by mlegenhausen** [comment]
Sounds reasonable. I would also allow `{ wordwrap: false }` or any other false value except `0`. A pull request is welcome :)

**Comment by tepez** [comment]
Cool @mlegenhausen. Will make one soon.
Seeing that there are no unit tests, do you mind if I add mocha/chai unit tests for this feature?

**Comment by mlegenhausen** [comment]
Unit tests are always welcome :) Haven't the time to add them by myself. I will review your pull request. This issue is closed for now further discussion in the pull request.
