### ISSUE TITLE
Relax node "engine" requirements.

### ISSUE THREAD

**Issue by nicholaswyoung** [werk85/node-html-to-text#40]
```
npm WARN engine html-to-text@0.1.0: wanted: {"node":"~0.8.0"} (current: {"node":"0.10.36","npm":"2.3.0"})
```
Everything seems to work fine outside of these boundaries. Maybe you can relax the engine requirements to include Node 0.10, 0.12, and IO.js 1.x.x?

**Comment by mlegenhausen** [comment]
Sure, a pull request is welcome :)

**Comment by nicholaswyoung** [comment]
Pull request submitted. For brevity sake, I added everything less than 1.4.x.
