### ISSUE TITLE
<li>these words each end on a new line</li>

### ISSUE THREAD

**Issue by webjay** [werk85/node-html-to-text#49]
When I set `wordwrap: false` the string `<li>these words each end on a new line</li>` becomes `these\nwords\neach\nend\non\na\nnew\nline`.

If I do not set set `wordwrap: false`, they don't.

**Comment by mlegenhausen** [comment]
Could you provide me an example file and your code? Could not reproduce this with the command line tool.

**Comment by webjay** [comment]
Sure, try this:

    describe('li bug', function () {
      it('fails', function () {
        var html = 'Good morning Jacob, \
   \
     \
      <p>Lorem ipsum dolor sit amet</p> \
     \
    <p><strong>Lorem ipsum dolor sit amet.</strong></p> \
    <ul> \
     \
      <li>run in the park <span style="color:#888888;">(in progress)</span></li> \
     \
    </ul> \
   \
  ';
        console.log(htmlToText.fromString(html, { wordwrap: false }));
      });
    });
