### ISSUE TITLE
remove console.log call in cli.js

### ISSUE THREAD

**Issue by glkz** [werk85/node-html-to-text#60]
[This line](https://github.com/werk85/node-html-to-text/blob/master/bin/cli.js#L13) pollutes the cli output. 

Instead, [visionmedia/debug](https://github.com/visionmedia/debug) may be used for this purpose.

**Comment by mlegenhausen** [comment]
Oh of cause this should not be there. Could you prepare a pull request? Thanks.

**Comment by glkz** [comment]
Sure.
