### ISSUE TITLE
Support Node 4 engine

### ISSUE THREAD

**Issue by dmyers** [werk85/node-html-to-text#64]
This currently throws the following warning trying to upgrade an app to Node 4:

```
npm WARN engine html-to-text@1.3.1: wanted: {"node":">= 0.8.0 <=0.12 || <3"} (current: {"node":"4.1.0","npm":"2.14.4"})
```

**Comment by mlegenhausen** [comment]
Pull request ist welcome ;)

**Comment by dmyers** [comment]
I'm honestly not sure what it should be set to. Could it just be removed? I haven't seen many modules use it.

**Comment by dmyers** [comment]
Added PR #65
