### ISSUE TITLE
linkHrefBaseUrl not set for html

### ISSUE THREAD

**Issue by DiknT** [werk85/node-html-to-text#76]
I can't figure out why the linkHrefBaseUrl is not set in the html version but correctly for the converted text version. I have set linkHrefBaseUrl in options and it is correctly build for text but missing for html, resulting in incomplete href:  href=3D'/auth/verify'

I have a very basic use case so far:

```javascript
import nodemailer from 'nodemailer'
import htmlToText from 'html-to-text'

const Mailer = nodemailer.createTransport(someTransporter(options))

const htmlToTextOptions = {
  linkHrefBaseUrl: 'http://domain.com'
}
Mailer.use('compile', async (mail, next) => {
  if (!mail.data.text && mail.data.html) {
    mail.data.text = await htmlToText.fromString(mail.data.html, htmlToTextOptions)
  }
  next()
})

const verificationUrl = '/auth/verify'
let body = `<b>Awesome sauce</b><br>
  <a href='${verificationUrl}'>Verify Account</a><br>
  Thank you!`

let mail = {
  to: some@email.com,
  from: 'other@email.com',
  subject: 'Registration',
  html: body
}
Mailer.sendMail(mail, (err, res) => {...})
```

Environment:
node 4.2
nodemailer: 2.0.0
node-html-to-text: 1.5.1

These are the resulting plain and html types as received by any mail client:

Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8
Mime-Version: 1.0

Awesome sauce
Verify Account [http://domain.com/auth/verify]
Thank you!=

Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8
Mime-Version: 1.0

<b>Awesome sauce</b><br>
          <a href=3D'/auth/verify'>Verify Account</a><br>
          Thank you!=

**Comment by mlegenhausen** [comment]
I can not see any error here related to `html-to-text`? When the html is wrong it seems to be a bug in your code.

**Comment by DiknT** [comment]
maybe I misunderstood the behavior of linkHrefBaseUrl. From the readme I get the idea that one can omit the baseUrl in the html href if linkHrefBaseUrl is set in the htmlToText options:

```linkHrefBaseUrl allows you to specify the server host for href attributes, where the links start at the root (/). For example, linkHrefBaseUrl = 'http://asdf.com' and <a href='/dir/subdir'>...</a> the link in the text will be http://asdf.com/dir/subdir```

Can you confirm that I should not need to include the full url in the html href if linkHrefBaseUrl is set? Thanks for your help
