### ISSUE TITLE
using --tables=true doesn't produce the expected results.

### ISSUE THREAD

**Issue by ELadner** [werk85/node-html-to-text#80]
Running the example/test.html as described on the main page results in the correctly formatted table, however if you change "--tables=#invoice,.address" to "--tables=true" (which should output all tables, not just the ones specified via class or ID) doesn't produce nicely formatted output.

According to the docs, this should be the case, but something is not getting set correctly.  I have a set of HTML I'm working on that has no class or ID information on the tables so the "--tables=true" is the only way I can get the output I need.

**Comment by mlegenhausen** [comment]
Ok it seems the cli has a bug where this does not work. You can try to run your only script and set `table: true` via the options.

**Comment by mlegenhausen** [comment]
Fixed in 1.6.1.
