### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by mazko** [werk85/node-html-to-text#81]
scenario:

    var htmlToText = require('html-to-text');
    htmlToText.fromString('&#128514;');

result is incorect:

    htmlToText.fromString('&#128514;')
    ''

Quick fix: replace  String.fromCharCode => String.fromCodePoint
 (polyfill https://github.com/mathiasbynens/String.fromCodePoint) 
in https://github.com/werk85/node-html-to-text/blob/master/lib/helper.js#L48

    require('string.fromcodepoint');
    String.fromCodePoint(128514)
    '😂'
    String.fromCharCode(128514)
    ''

**Comment by mlegenhausen** [comment]
Unicode support would of cause be nice, but I am not a fan of monkey patching even it is a polyfill and would more go in the direction of dropping support for old node versions. Do you know since which node version `fromCodePoint` is available?

**Comment by mazko** [comment]
```iojs``` seem to support native ```fromCodePoint``` https://davidwalsh.name/es6-io#new-string-methods

```String.fromCodePoint``` from mathiasbynens looks good enough + well tested (97% coverage) but yes  it's hard to debug for example if some submodule(s) has own polyfill impl, so which one was initialized first ?

    ~$ cat test.js
    String.badthing = 42

    $ node
    > String.badthing
    undefined
    > require('./test')
    {}
    > String.badthing
    42

Maybe this is why https://github.com/mathiasbynens/he not using own polyfill for same task )

**Comment by curiousdannii** [comment]
String.fromCodePoint is available in node 4+ https://kangax.github.io/compat-table/es6/#test-String_static_methods_String.fromCodePoint

Polyfills don't have to pollute the global namespace or modify the built in objects. You can easily do

`var fromCodePoint = String.fromCodePoint || function(){ /* polyfill */ }`

**Comment by mlegenhausen** [comment]
You can try out unicode support in version 2.0.0 available on npm.

**Comment by mazko** [comment]
It works. Tested on:

    ~$ npm -v
    1.4.28
    ~$ node -v
    v0.10.35

Thanks.
